### ISSUE TITLE
Followed channels that's hosting someone is showing as online

### ISSUE THREAD

**Issue by Hund** [RadicalEd360/streamlink-curses#1]
If I add a channel and that channel is hosting someone, that channel will appear as online. I would prefer if they could appear as offline. :)

**Comment by RadicalEd360** [comment]
i will look into this, it annoys me as well

**Comment by Hund** [comment]
Thanks! :)

**Comment by RadicalEd360** [comment]
no prob :D

**Comment by RadicalEd360** [comment]
alright, i have disabled them from showing as online, hosted streams will now appear as offline.
my eventual goal for this is to show them as Hosted and who they are hosting, but for now this should be ok.

**Comment by Hund** [comment]
Awesome! :)
