### ISSUE TITLE
Configurable color options

### ISSUE THREAD

**Issue by Hund** [RadicalEd360/streamlink-curses#3]
It would be nice if you could change the colors or at least disable them via either a flag and/or a config option. Right now they're a bit off for me.

![streamlink-curses](https://user-images.githubusercontent.com/320498/34346930-6f9fc14a-e9fd-11e7-8803-031f6a3b66bb.png)

**Comment by RadicalEd360** [comment]
its some sloppy code but it works :D i will clean it up later, i have added an example theme config file to help with the new feature, eventually i will implement a way to change colors on the fly via a keybind

**Comment by RadicalEd360** [comment]
![2017-12-26-034157_870x761_scrot](https://user-images.githubusercontent.com/7925769/34353667-16dcb4fe-e9ef-11e7-9383-6761c214bae1.png)

**Comment by Hund** [comment]
Cool! Is it possible to support all 16 colors? I can't use my black (wich is "dark gray") right now. I'm using the Solarized colorscheme. :)

![colors](https://user-images.githubusercontent.com/320498/34359263-b978576a-ea56-11e7-911e-b88a65e93067.png)

**Comment by RadicalEd360** [comment]
finished, it will support any color now, ive also added a script which will show you the colors that are available to your terminal and the number for it called colortest.py

**Comment by Hund** [comment]
Works great thanks! :)
